"""
Django settings for menu_backend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os

from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Корневой каталог проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ для генерации временных токенов доступа
SECRET_KEY = os.getenv('SECRET_KEY', 'nskncgurmxkgru')

# Включить или выключить режим отладки
DEBUG = bool(int(os.getenv('DEBUG', '1')))

# URL сайта для генерации QR-кодов
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")

# Допустимые значения адреса продакшн-сервера
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Допустимые значения адресов для CSRF или CORS
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1').split(',')
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://127.0.0.1').split(',')

# Использовать собственную модель для пользователей
AUTH_USER_MODEL = 'users.User'


INSTALLED_APPS = [
    # Модули Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Модули сторонних разработчиков
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'parler',
    'phonenumber_field',
    'rest_framework',
    'rest_framework.authtoken',
    'rosetta',
    # Наши собственные модули
    'users',
    'restaurants',
    'menus',
    'tariffs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'menu_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'menu_backend.wsgi.application'


# Настройки подключения к базе данных
DATABASES = {
    'testing': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'working': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Используем базу по умолчанию
DATABASES['default'] = DATABASES['working']


# Проверки надежности паролей пользователей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Язык по умолчанию
LANGUAGE_CODE = 'en'

# Поддерживаемые языки
LANGUAGES = (
    ('en', _("English")),
    ('ru', _('Russian')),
)

# Путь для сохранения файлов переводов
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Префикс URL для статических файлов
STATIC_URL = 'static/'

# Каталог для размещения статических файлов
STATIC_ROOT = BASE_DIR / 'static'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Настройки REST API
REST_FRAMEWORK = {
    # Для постраничной выдачи данных
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Права доступа по умолчанию - доступ только администратора.
    # Фактически для большинства классов будут определены более мягкие
    # права доступа.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    # Используем авторизацию пользователей по токенам
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

# Поддерживаемые языки
PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},
        {'code': 'ru'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False
    }
}

# Настройки записи информации в журнал
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'default'
        }
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
        'propagate': True
    },
    'formatters': {
        'default': {
            'format': "{asctime} [{levelname}] {message}",
            'style': "{"
        }
    }
}
