version: "3.7"

services:
  db:
    container_name: menuuuu_db
    restart: always
    image: postgres:13-alpine
    env_file:
      - .db.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - menuuu_network

  django:
    build:
      context: menu_backend
      dockerfile: Dockerfile
    container_name: menuuu_django
    env_file:
      - .django.env
    volumes:
      - static_volume:/menu_backend/static
      - media_volume:/menu_backend/media
      - logs_volume:/logs
    depends_on:
      - db
    networks:
      - menuuu_network
    restart: always

  nginx:
    image: nginx:1.19.2
    container_name: menuuu_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
      - logs_volume:/logs:rw
    networks:
      - menuuu_network
    depends_on:
      - django
      - db
    ports:
      - "8080:80"

volumes:
  static_volume:
  media_volume:
  db_volume:
  logs_volume:

networks:
  menuuu_network:
