# Generated by Django 4.1.5 on 2023-03-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantstaff',
            options={'ordering': ['pk'], 'verbose_name': 'restaurant ownership or employment', 'verbose_name_plural': 'restaurant ownerships or employments'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Nickname'),
        ),
    ]
