# Generated by Django 4.1.5 on 2023-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurantstaff_options_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_receipt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Average receipt price'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram_profile',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter_profile',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter profile URL'),
        ),
    ]
