# Generated by Django 4.1.5 on 2023-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
