# Generated by Django 4.1.5 on 2023-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menusection_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucourse',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
