# Generated by Django 4.1.5 on 2023-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menucourse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['pk'], 'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
        migrations.AlterModelOptions(
            name='menutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'menu Translation'},
        ),
    ]
